// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HotChocolate.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace GraphQLAPIDemo.Data.Models
{
    public partial class Author
    {
        public Author()
        {
            Books = new HashSet<Book>();
        }

        [Key]
        public Guid Id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        [Authorize(Policy = "Author.Name.Policy")]
        public string Name { get; set; }

        [InverseProperty("Author")]
        public virtual ICollection<Book> Books { get; set; }
    }
}