// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using HotChocolate.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;

namespace GraphQLAPIDemo.Data.Models
{
    [Index("AuthorId", Name = "IX_Books_AuthorId")]
    public partial class Book
    {
        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        [Authorize(Policy = "Book.Title.Policy")]
        public string Title { get; set; }
        [Required]
        [Column("ISBN")]
        [StringLength(50)]
        [Unicode(false)]
        public string Isbn { get; set; }
        public Guid AuthorId { get; set; }

        [ForeignKey("AuthorId")]
        [InverseProperty("Books")]
        public virtual Author Author { get; set; }
    }
}