// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GraphQLAPIDemo.Data.Models
{
    public partial class Fields
    {
        public Fields()
        {
            UserFieldAccess = new HashSet<UserFieldAccess>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid TableId { get; set; }
        [Required]
        public string FieldName { get; set; }
        [Required]
        public string FieldDataType { get; set; }
        public string FieldProperties { get; set; }
        [Column("fieldOrder")]
        public int FieldOrder { get; set; }

        [ForeignKey(nameof(TableId))]
        [InverseProperty(nameof(Tables.Fields))]
        public virtual Tables Table { get; set; }
        [InverseProperty("Field")]
        public virtual ICollection<UserFieldAccess> UserFieldAccess { get; set; }
    }
}