// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GraphQLAPIDemo.Data.Models
{
    public partial class UsersInGroup
    {
        [Key]
        public Guid UserId { get; set; }
        [Key]
        public Guid GroupId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.UsersInGroup))]
        public virtual Users User { get; set; }
    }
}