// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GraphQLAPIDemo.Data.Models
{
    public partial class Users
    {
        public Users()
        {
            UserFieldAccess = new HashSet<UserFieldAccess>();
            UserTableAccess = new HashSet<UserTableAccess>();
            UsersInGroup = new HashSet<UsersInGroup>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(255)]
        public string UserName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastLogin { get; set; }
        [Column("status")]
        public int? Status { get; set; }

        [InverseProperty("User")]
        public virtual ICollection<UserFieldAccess> UserFieldAccess { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UserTableAccess> UserTableAccess { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<UsersInGroup> UsersInGroup { get; set; }
    }
}