// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace GraphQLAPIDemo.Data.Models
{
    public partial class UserTableAccess
    {
        [Key]
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid TableId { get; set; }
        public int TableAccessLevel { get; set; }

        [ForeignKey(nameof(TableId))]
        [InverseProperty(nameof(Tables.UserTableAccess))]
        public virtual Tables Table { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Users.UserTableAccess))]
        public virtual Users User { get; set; }
    }
}