name: FoD SAST Scan and Import

on: [workflow_dispatch]

jobs:
  FoD-SAST-Scan-And-Import:
    runs-on: windows-latest

    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v2      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
        with:
          vs-version: 16.10
      - name: Setup Java
        uses: actions/setup-java@v1     # Required for ScanCentral Client and FoD Uploader
        with:
          java-version: 1.8
      - name: Setup Fortify ScanCentral Client
        uses: fortify-actions/setup-scancentral-client@v1
      - name: Setup Fortify on Demand Uploader
        uses: fortify-actions/setup-fod-uploader@v1
   
      #publish the code
      - name: build and deploy
        run: dotnet publish GraphQLAPIDemo.sln -c Debug -r win-x64 --self-contained -o publish
      #zip the package
      - name: Setup action-zip
        uses: vimtor/action-zip@v1.2
        with:
          files: publish/         
          dest: package.zip
      #- name: debug Zip
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: test-artifact
      #    path: ${{ github.workspace }}\package.zip
      #scan the package
      - name: Package Code + Dependencies
        run: scancentral package $PACKAGE_OPTS -o package.zip
        env:
          PACKAGE_OPTS: "-bt msbuild -bf GraphQLAPIDemo.sln"
      #- name: Upload package and start FoD scan
      # run: java -jar "$Env:FOD_UPLOAD_JAR" -z package.zip -aurl https://api.ams.fortify.com/ -purl https://ams.fortify.com/ -uc "$Env:FOD_USER" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
      # env: 
      #    FOD_URL: "https://ams.fortify.com/"
      #    FOD_API_URL: "https://api.ams.fortify.com/"
      #    FOD_TENANT: ${{ secrets.FOD_TENANT }}
      #    FOD_USER: ${{ secrets.FOD_USER }}
      #    FOD_PAT: ${{ secrets.FOD_PAT }}
      #    FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
      #    FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -I 1 -apf"
      #    FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'
      
      # Start Fortify on Demand SAST scan and wait until results complete. For more information on FoDUploader commands, see https://github.com/fod-dev/fod-uploader-java
      # TODO: Update ENV variables for your application and create the necessary GitHub Secrets.  Helpful hints:
      #   Credentials and release ID should be obtained from your FoD tenant (either Personal Access Token or API Key can be used).
      #   Automated Audit preference should be configured for the release's Static Scan Settings in the Fortify on Demand portal.
      - name: Download Fortify on Demand Universal CI Tool
        uses: fortify/gha-setup-fod-uploader@6e6bb8a33cb476e240929fa8ebc739ff110e7433
      - name: Perform SAST Scan
        run: java -jar $FOD_UPLOAD_JAR -z ${{ github.workspace }}\package.zip -aurl $FOD_API_URL -purl $FOD_URL -rid "$FOD_RELEASE_ID" -tc "$FOD_TENANT" -uc "$FOD_USER" "$FOD_PAT" $FOD_UPLOADER_OPTS -n "$FOD_UPLOADER_NOTES"
        env:
          FOD_URL: "https://ams.fortify.com/"
          FOD_API_URL: "https://api.ams.fortify.com/"
          FOD_TENANT: ${{ secrets.FOD_TENANT }}
          FOD_USER: ${{ secrets.FOD_USER }}
          FOD_PAT: ${{ secrets.FOD_PAT }}
          FOD_RELEASE_ID: ${{ secrets.FOD_RELEASE_ID }}
          FOD_UPLOADER_OPTS: "-ep 2 -pp 0 -I 1 -apf"
          FOD_UPLOADER_NOTES: 'Triggered by GitHub Actions (${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})'

      # Once scan completes, pull SAST issues from Fortify on Demand and generate SARIF output.
      - name: Export results to GitHub-optimized SARIF
        uses: fortify/gha-export-vulnerabilities@fcb374411cff9809028c911dabb8b57dbdae623b
        with:
          fod_base_url: "https://ams.fortify.com/"
          fod_tenant: ${{ secrets.FOD_TENANT }}
          fod_user: ${{ secrets.FOD_USER }}
          fod_password: ${{ secrets.FOD_PAT }}
          fod_release_id: ${{ secrets.FOD_RELEASE_ID }}

      # Import Fortify on Demand results to GitHub Security Code Scanning
      - name: Import Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./gh-fortify-sast.sarif
